# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "IMTI"
license = "Apache"
licenselink = "https://github.com/zhaohuabing/hugo-theme-cleanwhite/blob/master/LICENSE"
description = "IMTI theme"
homepage = "https://github.com/zhaohuabing/hugo-theme-cleanwhite"
tags = [ "minimal", "responsive", "blog","light", "clean", "search"]
features = ["disqus", "site search", "responsive", "google analytics", "side bar"]
min_version = 0.10

[author]
  name = "Craig Johnston"
  homepage = "https://github.com/cjimti"

# If porting an existing theme
[original]
  name = "Huabing Zhao"
  homepage = "https://github.com/zhaohuabing"
